version : '3'

services:
  mysql-haakma-org:
   restart: always
   image: mysql:5.7.18
   volumes:
    - /home/sido/mysql/production/haakma.org:/var/lib/mysql
    - /home/sido/mysql/dumps/haakma.org:/docker-entrypoint-initdb.d
   networks:
    - mysql-haakma-org
   environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes

networks:
  mysql-haakma-org: