version : '3'

services:
  jenkins-haakma-org:
    restart: always
    build: .
    ports:
     - 7000:8080
    volumes:
     - /home/jenkins/jenkins_home:/var/jenkins_home
     - /home/sido/backup:/home/backup
     - /home/sido/config:/home/config
     - /srv/www:/home/sites
     - /srv/maildirs:/home/mail
     - /etc/postfix:/home/config/postfix
     - /etc/dovecot:/home/config/dovecot
    networks:
     - haakmaorgmysql_haakma-network
     - bronsenprojectmysql_bronsenproject-network

networks:
  haakmaorgmysql_haakma-network:
    external: true
  bronsenprojectmysql_bronsenproject-network:
    external: true
