version : '3'

services:
  jenkins-haakma-org:
    build: .
    ports:
     - 7000:8080
    volumes:
     - /home/jenkins/jenkins_home:/var/jenkins_home/
     - /home/sido/backup:/home/backup
     - /srv/www:/home/sites
    restart: always
